name: pages

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  POETRY_VERSION: "1.2.2"
  PYTHON_VERSION: "3.10"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==${POETRY_VERSION}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Install Nox and doc dependencies
        run: poetry install --only nox,docs
      - name: Publish Docs
        run: poetry run nox -s docs_github_pages
