name: Python package

on:
  push:
    paths:
      - "dbt_serverless/**.py"
      - ".github/workflows/python.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "README.md"
      - "LICENSE.txt"

env:
  POETRY_VERSION: "1.2.2"
  PYTHON_VERSION: "3.10"

jobs:
  test:
    runs-on: ubuntu-latest  
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: projects/${{ secrets.PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@${{ secrets.PROJECT }}.iam.gserviceaccount.com
      - name: Install poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: |
              3.9
              3.10
          cache: poetry
      - name: Test with Nox
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Quality with Nox
        run: make quality
  poetry-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Validate Poetry Configuration and Lockfile Freshness
        run: poetry lock --check
